# --------------------------------------------------------------------------------------------------------
# NOTE:
# As of v1.1.0, travis will be no longer used since I decided to move from Google Cloud to AWS, since
# my GCP free account is now expired.
# I decided to move this from root to config directory since I might need this as a future reference.
# --------------------------------------------------------------------------------------------------------
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project deejaygeroso-285210
  - gcloud config set compute/zone asia-east1-a
  - gcloud container clusters get-credentials deejaygeroso-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - bash ./config/bash/setup_env.sh
script:
  # - docker run -e CI=true deejaygeroso/deejaygeroso npm install && npm run test
  - echo "Success"
deploy:
  provider: script
  script: bash ./config/bash/setup_env.sh && bash ./config/bash/deploy.sh
  on:
    branch: master
