apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  tls:
    - hosts:
        - deejaygeroso.com
      secretName: deejaygeroso.com
  rules:
    - http:
        paths:
          - backend:
              serviceName: app-node-port-service
              servicePort: http
            path: /
